### Insertion sorting

In [3]:
import numpy as np

In [4]:
a = np.random.randint(20, size=10)
a

array([ 7,  2,  9,  4, 16, 16,  6, 13,  3, 11])

In [7]:
def insertion_sort(a):
    for j in range(1, len(a)):
        key = a[j]
        i = j - 1
        while i >= 0 and a[i] > key:
            a[i + 1] = a[i]
            i -= 1
        a[i + 1] = key
    return a

In [8]:
insertion_sort(a)

array([ 2,  3,  4,  6,  7,  9, 11, 13, 16, 16])

### buble sort

In [9]:
def buble_sort(a):
    for i in range(len(a) - 1):
        for j in range(len(a) - i - 1):
            if a[j] > a[j + 1]:
                a[j], a[j + 1] = a[j + 1], a[j]
    return a

In [10]:
b = np.random.randint(20, size=10)
b

array([13, 18, 11,  8, 15, 12, 18, 16,  4,  8])

In [11]:
buble_sort(b)

array([ 4,  8,  8, 11, 12, 13, 15, 16, 18, 18])

### cocktail

In [45]:
def cocktail(a):
    min_i = 0
    max_i = len(a) - 1
    while True:
        for i in range(min_i, max_i):
            if a[i] > a[i + 1]:
                a[i], a[i + 1] = a[i + 1], a[i]
        max_i -= 1
        #print(a)
        for i in range(max_i, min_i, -1):
            if a[i] < a[i - 1]:
                a[i - 1], a[i] = a[i], a[i - 1]
        min_i += 1
        #print(a)
        if min_i >= max_i:
            break
    return a

In [46]:
c = np.random.randint(20, size=9)
c

array([14, 12,  1,  8,  2,  4,  1,  8, 12])

In [47]:
cocktail(c)

array([ 1,  1,  2,  4,  8,  8, 12, 12, 14])

In [49]:
count = 0
for i in range(1000):
    for m in range(3, 20):
        c = np.random.randint(20, size=10)
        sort_c = cocktail(c)
        for i in range(len(sort_c) - 1):
            if sort_c[i] > sort_c[i + 1]:
                count = count + 1
print("accuracy: {}".format(1 - count/100))

accuracy: 1.0
